;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	delete-horizontal-space
	electric-newline-and-maybe-indent
	forward-sentence
	html-comment-line
	icicle-yank-maybe-completing
	indent-for-tab-command
	kill-region
	nxml-electric-slash
	toggle-input-method
	yank-rectangle
	))

(setq mc/cmds-to-run-once
      '(
	))
